### ISSUE TITLE
Slow network mode

### ISSUE THREAD

**Issue by vmdsb** [rubenmv/chrome-extension-tabs-queue#2]
Hi Ruben,
I hope you are ok.
I'm happy to see you introduced the "Slow network mode" inspired on my previous comment.
It helps because I use the "link clump extension" to open dozens of links at once.
You say: "If number of current loading tabs reaches this limit, queued items won't be released even if there's enough free spaces."
I suggest that when there are excessive loading tabs, two things should be forbidden:
a) -forbid releasing queued tabs (already in work, congradulations)
b) -forbid new clicked links to be opened, therefore, all new clicked links should go directly to the end of the queue.
Unfortunately this b) is not implemented. Therefore, I open 20 Facebook links at once, and all of them are loading, even if I set "Slow network mode-Limit: 2", (that is terrible for overloading CPU and causing incomplete pages).
Furthermore, I suggest that the excessive clicked links go directly to the end of the queue before they start loading (idealy, no tab should apear). At this version, the extension is able to remove the tab after opening. Isn't it possible to prevent th tab from appearing, and, discretely, store the link in the queue, without any flashing tab at all?
Thanks, and sorry for the suggestions, I'm just trying to contribute to your good work...
Saludos,
Vitor

**Comment by rubenmv** [comment]
Hi again, don't need to be sorry, I'm always open to suggestions. I'm glad you're still interested in the extension.

About the case "b", I'll look into that, it should check first the slow network limit but It doesn't seem to be working now.

But I can't do anything about tabs opening before going into queue, I've tried but the Chrome API doesn't provide with any means to get a tab before it opens and It won't allow me to capture some keyboard/mouse commands either (like Ctrl+LMB). So for now there's no way to do it, sorry.

Thanks and I'll look into that second case.

**Comment by vmdsb** [comment]
Hi Ruben,

Thanks for your attention and reply. I believe you can develop a solution for b) (queue newly created tabs when excessively active tabs are already loading simultaneously). No doubt you will be able to program that in your extension.

The other suggestion is rather difficult: As you explained: "...can't do anything about tabs opening before
 going into queue...". Anyway, extensions such as "VIEW LATER" are able to add a right-click menu option, ant the link passes directly to the list, without any tab appearing at all. You should see that example. Anyway it can't "catch" the external thrown links before the browser creates tabs. 

Therefore, you already have a menu option: "Open link in new tab (don't) queue". 

In the same way, you might create another one (below that one, in that context menu) like "Send link directly to queue, (don't open any tab)".

Other extensions, such as "LINK CLUMP" (which I use permanently) have an option to drag the right button over all the dozens of links to send them to clipboard, and no tab is opened.

Other interesting options on the context menu, could be: "Close tab and save/add it at the end of the queue".

I can't find the "Queue to fit limit" button. It's not in the context menu, neither in the icon menu. Anyway, I often feel the need to decrease (or increase) the allowed limit of tabs. So, ideally, this should work dynamically. I mean: if I have 20 tabs opened, decreasing the limit to 15, would cause suddenly the last 5 to be closed to queue. On the other hand, increasing the allowed limit to 20, the oldest 5 links would be instantly opened in new tabs. The icon menu should have the limit settings because it's not so practical to go often to the options page.

Sorry for the long message. 
Once again, you don't need to do nothing, even no reply is expected from me. This was simply a way of expressing some random ideas I have to someone, because other developers don't even read my messages. I can't know it they even open my suggestions. Other become upset because they see this as a complaint or order...

Thanks,
vitor

---

On Fri, 4/29/16, Ruben Martinez notifications@github.com wrote:

 Subject: Re: [rubenmv/chrome-extension-tabs-queue] Slow network mode (#2)
 To: "rubenmv/chrome-extension-tabs-queue" chrome-extension-tabs-queue@noreply.github.com
 Cc: "vmdsb" vmdsb@yahoo.com, "Author" author@noreply.github.com
 Date: Friday, April 29, 2016, 12:32 AM

 Hi again, don't need to be
 sorry, I'm always open to suggestions. I'm glad
 you're still interested in the extension.

 About the case "b", I'll look into that, it
 should check first the slow network limit but It doesn't
 seem to be working now.

 But I can't do anything about tabs opening before
 going into queue, I've tried but the Chrome API
 doesn't provide with any means to get a tab before it
 opens and It won't allow me to capture some
 keyboard/mouse commands either (like Ctrl+LMB). So for now
 there's no way to do it, sorry.

 Thanks and I'll look into that second case.

 —
 You are receiving this because you authored the thread.
 Reply to this email directly or view
 it on GitHub
