### ISSUE TITLE
Proactively queue tabs

### ISSUE THREAD

**Issue by KurtPoehler** [rubenmv/chrome-extension-tabs-queue#3]
there is no option to send a tab to the queue. Is there going to by such option?

**Comment by Blagatt** [comment]
I second this. Please @rubenmv :D

**Comment by rubenmv** [comment]
Sorry for not saying anything before, personal problems and life in general forced to completely disconnect from some projects. I just wanted to say that I just added two context menu entries to manually send tabs and links directly to the queue, those will be available in the next version. I'll try to release it within the next few days.

**Comment by vmdsb** [comment]
Hi Ruben,That's a Great feature! (Long requested by many.)Thanks once again.Good luck on 2018 and Merry Christmas.Regards, Vítor Barata 

    On Tuesday, November 28, 2017, 11:40:57 PM GMT, Ruben Martinez <notifications@github.com> wrote:  
 
 
Sorry for not saying anything before, personal problems and life in general forced to completely disconnect from some projects. I just wanted to say that I just added two context menu entries to manually send tabs and links directly to the queue, those will be available in the next version. I'll try to release it within the next few days.
