### ISSUE TITLE
Option to limit tabs across all windows

### ISSUE THREAD

**Issue by eorroe** [rubenmv/chrome-extension-tabs-queue#6]

**Comment by rubenmv** [comment]
Please be more specific about the behaviour you want. If this is what I think it is, it would mess up with saved queues and everything, a single new tab on a new window will close intermediately and create a new saved queue with just one tab, for example. Why not just use a lower limit?

**Comment by eorroe** [comment]
I suppose, I actually just wanted to get an idea of how this would work. Not a priority feature request

**Comment by wis** [comment]
Oh, so that's why it's not working for me, I have hundreds of opened tabs in tens of windows,
who opens more than 10 tabs in one window? you can't read the title of the tab if you do..

**Comment by eorroe** [comment]
I don't anymore thanks to this extension, but yea there are plenty of people who do. Just check twitter for "tab overload"
