### ISSUE TITLE
Add tab to Queue

### ISSUE THREAD

**Issue by pedrofuentes** [rubenmv/chrome-extension-tabs-queue#8]
As a user I would like to be able to manually add tabs to the queue.

**Comment by eorroe** [comment]
Yes via a shortcut that'd be awesome

**Comment by rubenmv** [comment]
Hi, I'm back on doing some stuff for the extension, I just added two context menu entries to manually send tabs and links directly to the queue. I'm closing this and I'll try to release a new version within the next few days.
